apiVersion: v1
kind: Service
metadata:
  name: ansible-manager
  labels:
    app: ansible-manager
spec:
  type: NodePort
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 30025
  selector:
    app: ansible-manager